Repository MicroHealthLLC/mPATH, pull requests merged in 2021-03, with the labels that each got.

#1961 Admin labels etc lisa mar 5 and 8
  app/admin/facilities.rb
  app/admin/facility_groups.rb
  app/admin/issues.rb
  app/admin/projects.rb
  app/admin/risks.rb
  app/admin/tasks.rb
  app/admin/users.rb
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/shared/filter_sidebar.vue
  app/javascript/components/users/profile.vue
  app/javascript/store/index.js
Labels: enhancement

#2070 Debugging QA Risk form.
  app/assets/stylesheets/common.scss
  app/javascript/components/dashboard/risks/risk_form.vue
Labels: Priority, bug

#2152 Re-designed Checklist/Control tab in Task, Issues, and Risk forms
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: Priority, enhancement

#2223 2161: Replaced Stages dropdown with graphical stage selection
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/shared/kanban.vue
Labels: Priority, enhancement
