Repository MicroHealthLLC/mPATH, pull requests merged in 2021-04, with the labels that each got.

#2243 2242 - section admin tasks forms
  app/admin/tasks.rb
Labels: security findings

#2245 2244 - section admin issues forms
  app/admin/issues.rb
Labels: security findings

#2249 2248 - admin user forms tab and header
  app/admin/users.rb
Labels: security findings

#2250 2246 - stage on forms without write
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2251 2200 - admin risks filters email checklists
  app/admin/risks.rb
Labels: security findings

#2254 Adding Favorite Filter feature
  app/controllers/query_filters_controller.rb
  app/javascript/components/shared/filter_sidebar.vue
  app/models/favorite_filter.rb
  app/models/project.rb
  app/models/query_filter.rb
  db/migrate/20210401200944_create_favorite_filters.rb
  db/migrate/20210401201418_add_favorite_filter_id_to_query_filters.rb
  db/schema.rb
  lib/tasks/update_database.rake
Labels: security findings

#2264 433
  app/javascript/components/shared/filter_sidebar.vue
Labels: security findings

#2258 2246 - disable stage selector without write
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2259 admin action tabs
  app/admin/issues.rb
  app/admin/tasks.rb
  vendor/assets/javascripts/active_admin.js
  vendor/assets/stylesheets/active_admin.scss
Labels: security findings

#2265 1846 - checklist progress action read only
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2280 Sort by first name hotfix request.
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/issues/issue_sheets_index.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
  app/models/issue.rb
  app/models/risk.rb
  app/models/task.rb
Labels: Priority

#2277 Revert Stage bar
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2274 adding share in favorite filters
  app/controllers/application_controller.rb
  app/controllers/query_filters_controller.rb
  app/javascript/components/shared/filter_sidebar.vue
  app/models/favorite_filter.rb
Labels: security findings

#2289 Admin fix
  app/admin/issues.rb
  app/admin/risks.rb
  app/admin/task_types.rb
  app/admin/tasks.rb
  app/admin/users.rb
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#2301 Route reconfiguration
  Gemfile.lock
  app/assets/stylesheets/common.scss
  app/controllers/projects_controller.rb
  app/javascript/components/dashboard/facilities/facility_show.vue
  app/javascript/components/dashboard/index.vue
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/issues/issue_index.vue
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/issues/issue_sheets_index.vue
  app/javascript/components/dashboard/issues/issue_show.vue
  app/javascript/components/dashboard/notes/notes_form.vue
  app/javascript/components/dashboard/notes/notes_sheets.vue
  app/javascript/components/dashboard/notes/notes_show.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/risks/risk_index.vue
  app/javascript/components/dashboard/risks/risk_show.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/dashboard/tasks/task_index.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_show.vue
  app/javascript/components/shared/ProjectRollup.vue
  app/javascript/components/shared/ProjectSidebar.vue
  app/javascript/components/shared/ProjectTabs.vue
  app/javascript/components/shared/kanban.vue
  app/javascript/components/shared/state_facility_sidebar.vue
  app/javascript/components/shared/tabsbar.vue
  app/javascript/components/views/kanban/KanbanDefault.vue
  app/javascript/components/views/kanban/KanbanIssueForm.vue
  app/javascript/components/views/kanban/KanbanIssues.vue
  app/javascript/components/views/kanban/KanbanRiskForm.vue
  app/javascript/components/views/kanban/KanbanRisks.vue
  app/javascript/components/views/kanban/KanbanTaskForm.vue
  app/javascript/components/views/kanban/KanbanTasks.vue
  app/javascript/components/views/kanban/KanbanView.vue
  app/javascript/components/views/map/MapIssueForm.vue
  app/javascript/components/views/map/MapIssues.vue
  app/javascript/components/views/map/MapNoteForm.vue
  app/javascript/components/views/map/MapNotes.vue
  app/javascript/components/views/map/MapOverview.vue
  app/javascript/components/views/map/MapRiskForm.vue
  app/javascript/components/views/map/MapRisks.vue
  app/javascript/components/views/map/MapTaskForm.vue
  app/javascript/components/views/map/MapTasks.vue
  app/javascript/components/views/map/MapView.vue
  app/javascript/components/views/sheet/SheetIssueForm.vue
  app/javascript/components/views/sheet/SheetIssues.vue
  app/javascript/components/views/sheet/SheetNoteForm.vue
  app/javascript/components/views/sheet/SheetNotes.vue
  app/javascript/components/views/sheet/SheetOverview.vue
  app/javascript/components/views/sheet/SheetRiskForm.vue
  app/javascript/components/views/sheet/SheetRisks.vue
  app/javascript/components/views/sheet/SheetTaskForm.vue
  app/javascript/components/views/sheet/SheetTasks.vue
  app/javascript/components/views/sheet/SheetView.vue
  app/javascript/routers/dashboard.js
  app/views/layouts/_landing.html.slim
  config/routes.rb
Labels: security findings

#2302 fix gem error
  Gemfile.lock
Labels: security findings

#2304 Scaled form tabs down in map view to prevent getting clipped.
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/shared/FormTabs.vue
Labels: security findings

#2316 Form breadcrumb links now active
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2320 Added scrollbar to Sheet view pages
  app/javascript/components/views/sheet/SheetView.vue
Labels: security findings

#2323 Added vertical scrollbar for Kanban view.
  app/javascript/components/shared/kanban.vue
  app/javascript/components/views/kanban/KanbanView.vue
Labels: security findings

#2322 fix issue #2311 #2312 #2315 #2306
  app/controllers/profiles_controller.rb
  app/javascript/components/users/profile.vue
  app/models/user.rb
  app/views/layouts/_landing.html.slim
  config/routes.rb
Labels: security findings

#2324 Map tooltip shows on page refresh for current project.
  app/javascript/components/dashboard/tasks/task_index.vue
  app/javascript/components/views/map/MapView.vue
Labels: security findings

#2336 Kanban refresh and persistence fixes for cards
  app/javascript/components/views/kanban/KanbanDefault.vue
  app/javascript/components/views/kanban/KanbanIssues.vue
  app/javascript/components/views/kanban/KanbanRisks.vue
  app/javascript/components/views/kanban/KanbanTasks.vue
  app/javascript/components/views/kanban/KanbanView.vue
Labels: security findings

#2344 Kanban new form stage fixes
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/views/kanban/KanbanIssueForm.vue
  app/javascript/components/views/kanban/KanbanIssues.vue
  app/javascript/components/views/kanban/KanbanRiskForm.vue
  app/javascript/components/views/kanban/KanbanRisks.vue
  app/javascript/components/views/kanban/KanbanTaskForm.vue
  app/javascript/components/views/kanban/KanbanTasks.vue
  app/javascript/routers/dashboard.js
Labels: security findings

#2341 Add success indicator message when moving kanban cards
  app/javascript/components/shared/kanban.vue
  app/javascript/store/index.js
Labels: security findings

#2365 fix due date
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/models/user.rb
Labels: security findings

#2357 Fixed scroll point on Risk Form to match Task and Issue
  app/javascript/components/dashboard/risks/risk_form.vue
Labels: security findings

#2364 Changed inputs to el-inputs and prevented tags from extending the inp…
  app/javascript/components/views/kanban/KanbanIssues.vue
  app/javascript/components/views/kanban/KanbanRisks.vue
  app/javascript/components/views/kanban/KanbanTasks.vue
Labels: security findings

#2370 Upgraded 'is-svg' dependency to resolve high-vulnerability security warning (ie, dependabot alert)
  package.json
  yarn.lock
Labels: Priority, dependencies, security findings

#2372 Fixed Risk Approval section issues. Ready for testing.
  app/javascript/components/dashboard/risks/risk_form.vue
Labels: Priority

#2373 Fixed Overview Apply save function on Map and Sheet
  app/javascript/components/views/map/MapOverview.vue
  app/javascript/components/views/map/MapView.vue
  app/javascript/components/views/sheet/SheetOverview.vue
  app/javascript/components/views/sheet/SheetView.vue
Labels: security findings

#2374 Removed horizontal scrollbar on Task and Issue forms on Map View.
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2377 Fixed Issue Form width on Kanban view.
  app/javascript/components/dashboard/issues/issue_form.vue
Labels: security findings

#2388 Change app name from mGIS to mPATH
  app/assets/images/mpath.png
  app/assets/stylesheets/common.scss
  app/javascript/components/dashboard/risks/risk_form.vue
  app/views/layouts/_head_items.html.slim
  app/views/layouts/_landing.html.slim
Labels: enhancement

#2391 Lessons table sorting
  app/assets/stylesheets/common.scss
  app/javascript/components/views/lessons/LessionForm.vue
  app/javascript/components/views/lessons/LessionsIndex.vue
Labels: security findings

#2393 mPATH name updated in Admin Panel.
  config/initializers/active_admin.rb
Labels: enhancement

#2387 Map/Sheet Overview - Display correct data after navigation changes
  app/javascript/components/views/map/MapOverview.vue
  app/javascript/components/views/map/MapView.vue
  app/javascript/components/views/sheet/SheetOverview.vue
  app/javascript/components/views/sheet/SheetView.vue
Labels: security findings

#2397 Test suites for release
  spec/cypress/integration/admin_panel/categories/categories_spec.js
  spec/cypress/integration/admin_panel/programs/program_types_spec.js
  spec/cypress/integration/admin_panel/programs/programs_spec.js
  spec/cypress/integration/admin_panel/projects/project_groups_spec.js
  spec/cypress/integration/admin_panel/projects/projects_spec.js
  spec/cypress/integration/admin_panel/projects/statuses_spec.js
  spec/cypress/integration/client_panel/admin_user/kanban/risks_spec.js
  spec/cypress/integration/client_panel/admin_user/sheet/notes_spec.js
  spec/cypress/integration/client_panel/client_user/sheet/notes_spec.js
  spec/cypress/support/commands.js
  spec/cypress/support/risks.js
Labels: security findings

#2395 Update program summary after status or due date change
  app/javascript/components/shared/ProjectRollup.vue
  app/javascript/components/views/map/MapOverview.vue
  app/javascript/components/views/sheet/SheetOverview.vue
Labels: security findings

#2403 Disabled stage change for users without permission.
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2406 fix issue
  app/models/user.rb
Labels: security findings

#2407 adding reset filter button
  app/javascript/components/shared/filter_sidebar.vue
Labels: security findings

#2413 Fixed extra scrollbar on Risk Form
  app/javascript/components/dashboard/risks/risk_form.vue
Labels: security findings

#2422 2332
  app/controllers/application_controller.rb
  app/controllers/query_filters_controller.rb
  app/javascript/components/dashboard/facilities/facility_rollup.vue
  app/javascript/components/shared/filter_sidebar.vue
  app/models/favorite_filter.rb
Labels: security findings

#2421 Deselect project by clicking on empty space of Project Sidebar
  app/javascript/components/shared/ProjectSidebar.vue
Labels: security findings

#2419 Maintain project context when switching from tab to tab
  app/javascript/components/shared/tabsbar.vue
  app/javascript/components/views/kanban/KanbanView.vue
  app/javascript/components/views/map/MapView.vue
  app/javascript/components/views/sheet/SheetView.vue
Labels: security findings

#2431 Maintain context after tab switch.
  app/javascript/components/shared/tabsbar.vue
Labels: security findings

#2433 fix issue with profile
  app/javascript/components/users/profile.vue
  app/models/user.rb
Labels: security findings

#2434 Gantt route fix
  app/javascript/components/shared/tabsbar.vue
Labels: security findings

#2435 fix project group issue
  app/javascript/components/shared/filter_sidebar.vue
  app/javascript/store/index.js
  app/models/project.rb
Labels: security findings

#2445 Reset Map Boundary Filter added to Reset button.
  app/javascript/components/shared/filter_sidebar.vue
Labels: security findings

#2458 send only active projects
  app/models/project.rb
Labels: security findings
