Repository MicroHealthLLC/mPATH, pull requests merged in 2021-05, with the labels that each got.

#2405 Lessons
  app/admin/lessons.rb
  app/admin/users.rb
  app/assets/stylesheets/common.scss
  app/controllers/lessons_controller.rb
  app/controllers/projects_controller.rb
  app/javascript/components/dashboard/sheets.vue
  app/javascript/components/shared/tabsbar.vue
  app/javascript/components/views/lessons/LessonForm.vue
  app/javascript/components/views/lessons/LessonsIndex.vue
  app/javascript/routers/dashboard.js
  app/javascript/store/index.js
  app/models/ability.rb
  app/models/lesson.rb
  app/models/lesson_detail.rb
  app/models/lesson_project.rb
  app/models/lesson_user.rb
  app/models/project.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20210412174000_create_lessons.rb
  db/migrate/20210419213115_create_lesson_users.rb
  db/migrate/20210420204037_add_lessons_to_privileges.rb
  db/migrate/20210421055825_create_lesson_details.rb
  db/migrate/20210423201422_create_lesson_projects.rb
  db/schema.rb
  db/seeds.rb
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#2481 fix duplicate inputbox issue
  app/admin/facilities.rb
Labels: security findings

#2482 Fixed country code UI in Admin Panel.
  app/admin/facilities.rb
  vendor/assets/stylesheets/active_admin.scss
Labels: HOTFIX

#2528 Task Form - Related Tasks, Issues, and Risks
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/shared/RelatedContextMenu.vue
Labels: security findings

#2539 Program name row increased in height in Welcome Page
  app/assets/stylesheets/common.scss
  app/views/layouts/_landing.html.slim
Labels: security findings

#2540 Related Tasks, Issues, and Risks restrcuture.
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/shared/RelatedIssueMenu.vue
  app/javascript/components/shared/RelatedRiskMenu.vue
  app/javascript/components/shared/RelatedTaskMenu.vue
Labels: security findings

#2542 Delete search input after blur.
  app/javascript/components/shared/RelatedIssueMenu.vue
  app/javascript/components/shared/RelatedRiskMenu.vue
  app/javascript/components/shared/RelatedTaskMenu.vue
Labels: security findings

#2515 fix security issue by upgrading rails version
  Gemfile
  Gemfile.lock
Labels: security findings

#2568 Fix margins.
  app/javascript/components/dashboard/issues/issue_form.vue
Labels: security findings

#2566 Current stage same color as completed stages.
  app/assets/stylesheets/common.scss
Labels: security findings

#2555 hiding latitude and longitude
  app/admin/users.rb
Labels: security findings

#2584 Expand project tree if there is only one group
  app/javascript/components/shared/ProjectSidebar.vue
Labels: security findings

#2589 Fixed calendar reload rerendering issue; added improved mPATH logo in…
  app/assets/images/microhealth.svg
  app/assets/images/mpath.svg
  app/assets/stylesheets/common.scss
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
  app/javascript/components/views/calendar/CalendarLanding.vue
  app/views/layouts/_landing.html.slim
Labels: security findings

#2613 Fixed Calendar forms breadcrumbs issue (Ref: #2601)
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2627 Fixed special characters bug in pdf exports Last Update column.
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/issues/issue_index.vue
  app/javascript/components/dashboard/issues/issue_sheets_index.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/risks/risk_index.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/dashboard/tasks/task_index.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
Labels: bug, javascript

#2629 Disable remove button based on privilege.
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#2641 Added Context Menu and Show All toggle to Calendar View.
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
Labels: Priority

#2640 Add close button on related menus.
  app/javascript/components/shared/RelatedIssueMenu.vue
  app/javascript/components/shared/RelatedRiskMenu.vue
  app/javascript/components/shared/RelatedTaskMenu.vue
Labels: security findings

#2639 Enable Related Context Menus for new forms.
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/shared/RelatedRiskMenu.vue
Labels: security findings

#2638 Enable Related Context Menus for new forms.
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/shared/RelatedIssueMenu.vue
Labels: security findings

#2643 FInished Calendar View context menu UI.
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
Labels: Priority

#2644 Fixed Category filters and left click bug in Calendar view context menus
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
Labels: Priority, bug

#2650 Fixed bug related to showing more events.
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
Labels: bug

#2653 Upgrading puma to 5.3.2
  Gemfile
  Gemfile.lock
Labels: security findings

#2661 2660 - edit project edit assigned program
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#2699 1999 sort column risk stage
  app/admin/issues.rb
  app/admin/risks.rb
Labels: security findings

#2697 2181r1 remove on watch and facility manager
  app/controllers/projects_controller.rb
  config/routes.rb
Labels: security findings
