Repository MicroHealthLLC/mPATH, pull requests merged in 2021-07, with the labels that each got.

#2973 Fixed alignment issue on Lesson form
  vendor/assets/stylesheets/active_admin.scss
Labels: security findings

#2971 Fixed width issue filter lesson details
  vendor/assets/stylesheets/active_admin.scss
Labels: security findings

#2960 Updates and Description truncate.
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
  app/javascript/components/views/sheet/SheetLessons.vue
Labels: security findings

#2957 Fix notes issue and removed unwanted file
  app/controllers/facilities/notes_controller.rb
  app/controllers/notes_controller.rb
  config/routes.rb
Labels: security findings

#2975 LessonDetail|Filter: Detail type updated to search and select
  app/admin/lesson_details.rb
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#2976 EditUser|Project: Search and select program
  app/views/admin/facility_privileges/facility_privilege_form.html.slim
  app/views/admin/facility_privileges/facility_privileges_partial.html.slim
Labels: security findings

#2982 2981 checkbox column with admin write priv
  app/admin/risks.rb
Labels: security findings

#2979 Delete unused components
  app/javascript/components/dashboard/kanban_view.vue
  app/javascript/components/dashboard/map_view.vue
  app/javascript/components/dashboard/sheets.vue
  app/javascript/components/shared/ProjectRollup.vue
  app/javascript/components/shared/ProjectSidebar.vue
  app/javascript/components/views/lessons/LessonForm.vue
  app/javascript/components/views/lessons/LessonsIndex.vue
  app/javascript/routers/dashboard.js
Labels: security findings

#2985 Risk: program and project changed to search and select
  app/admin/risks.rb
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#2983 2980 checkbox column with admin write priv
  app/admin/issues.rb
Labels: security findings

#3001 Trying to fix performance issue on front end
  app/assets/javascripts/application.js
  app/javascript/components/shared/filter_sidebar.vue
  app/javascript/store/index.js
Labels: security findings

#2998 Fix routing issue
  app/javascript/components/users/profile.vue
  app/models/user.rb
Labels: security findings

#3005 Allow lesson to read with default setting on map view
  app/javascript/components/views/map/MapLessons.vue
Labels: security findings

#3012 Fixed alignment on task & issue form
  vendor/assets/stylesheets/active_admin.scss
Labels: security findings

#3013 3008, 3009, and 3010 Fixes
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
  app/javascript/components/shared/kanban.vue
Labels: security findings

#3018 Assign default privilege
  app/models/privilege.rb
  lib/tasks/update_database.rake
Labels: security findings

#3019 make gantt view working
  app/javascript/store/index.js
Labels: security findings

#3020 Risk|Filters: Owned by should be multiselect
  app/admin/risks.rb
  app/models/user.rb
Labels: security findings

#3027 Lesson|Filter: Style update from green to blue
  app/admin/lessons.rb
Labels: security findings

#3025 Issue|Filter: Style update from green to blue
  app/admin/issues.rb
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#3030 Adding presence validation in lesson detail
  app/admin/lessons.rb
  app/models/ability.rb
  app/models/lesson.rb
  app/models/lesson_detail.rb
Labels: security findings

#3021 Risk|Filter: Style update from green to blue
  app/admin/risks.rb
Labels: security findings

#3043 Added info on UI telling user Findings is required
  app/javascript/components/dashboard/lessons/LessonForm.vue
Labels: security findings

#3050 Admin|Lesson: Recommendation should not be required
  app/models/lesson_detail.rb
Labels: enhancement

#3042 Admin Lesson Added by
  app/admin/lessons.rb
Labels: enhancement

#3054 Resolving high-severity dependabot alert for trim-newlines dependency.
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  package.json
  yarn.lock
Labels: Dependabot Alert

#3056 LessonDetails: detail type filter should not be preselected
  app/admin/lesson_details.rb
Labels: enhancement

#3057 Resolving high-severity dependabot alert for glob-parent dependency.
  app/javascript/components/dashboard/risks/risk_show.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
  package.json
  yarn.lock
Labels: Dependabot Alert

#3059 Fix: nomethod error in projects controller
  app/models/issue.rb
  app/models/risk.rb
  app/models/task.rb
Labels: security findings

#3058 Stages sorted by percentage in forms and Kanban
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/shared/kanban.vue
Labels: security findings

#3061 Lesson: Modified title to name on filter and index
  app/admin/lessons.rb
Labels: enhancement

#3063 Moved advanced tab in admin user
  app/admin/users.rb
Labels: security findings

#3064 Fix issue with admin user privilege box
  app/controllers/facility_privileges_controller.rb
  app/models/facility_privilege.rb
  app/views/admin/facility_privileges/_list_facility_privileges.html.slim
  app/views/admin/facility_privileges/facility_privilege_form.html.slim
  app/views/admin/facility_privileges/facility_privileges_partial.html.slim
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#3060 Fix issue with privileges
  app/javascript/components/dashboard/gantt_view.vue
  app/javascript/components/views/kanban/KanbanIssues.vue
  app/javascript/components/views/kanban/KanbanRisks.vue
  app/javascript/components/views/kanban/KanbanTasks.vue
  app/javascript/components/views/map/MapLessons.vue
  app/models/facility_privilege.rb
  app/models/project_privilege.rb
Labels: security findings

#3086 Adding environment variable to set portfolio name
  app/javascript/components/views/portfolio/PortfolioView.vue
  app/javascript/packs/portfolio.js
  app/views/dashboard/portfolio.html.slim
Labels: security findings

#3085 Treat admin user as normal in client panel
  app/javascript/components/dashboard/facilities/facility_show.vue
  app/javascript/components/dashboard/gantt_view.vue
  app/javascript/components/dashboard/issues/issue_calendar.vue
  app/javascript/components/dashboard/issues/issue_form.vue
  app/javascript/components/dashboard/issues/issue_index.vue
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/issues/issue_sheets_index.vue
  app/javascript/components/dashboard/issues/issue_show.vue
  app/javascript/components/dashboard/lessons/LessonForm.vue
  app/javascript/components/dashboard/notes/notes_form.vue
  app/javascript/components/dashboard/notes/notes_index.vue
  app/javascript/components/dashboard/notes/notes_sheets.vue
  app/javascript/components/dashboard/notes/notes_sheets_index.vue
  app/javascript/components/dashboard/notes/notes_show.vue
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/risks/risk_form.vue
  app/javascript/components/dashboard/risks/risk_index.vue
  app/javascript/components/dashboard/risks/risk_show.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
  app/javascript/components/dashboard/tasks/task_form.vue
  app/javascript/components/dashboard/tasks/task_index.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_show.vue
  app/javascript/components/shared/ContextMenu.vue
  app/javascript/components/shared/IssueContextMenu.vue
  app/javascript/components/shared/LessonContextMenu.vue
  app/javascript/components/shared/RelatedIssueMenu.vue
  app/javascript/components/shared/RelatedLessonMenu.vue
  app/javascript/components/shared/RelatedRiskMenu.vue
  app/javascript/components/shared/RelatedTaskMenu.vue
  app/javascript/components/shared/RiskContextMenu.vue
  app/javascript/components/shared/filter_sidebar.vue
  app/javascript/components/shared/kanban.vue
  app/javascript/components/views/kanban/KanbanIssues.vue
  app/javascript/components/views/kanban/KanbanRisks.vue
  app/javascript/components/views/kanban/KanbanTasks.vue
  app/javascript/components/views/map/MapLessons.vue
  app/javascript/components/views/map/MapOverview.vue
  app/javascript/components/views/sheet/SheetLessons.vue
  app/javascript/components/views/sheet/SheetOverview.vue
  app/models/privilege.rb
  app/models/user.rb
  app/views/layouts/_landing.html.slim
  db/migrate/20210714170838_remove_default_value_from_privileges.rb
Labels: security findings

#3084 Fixed dates showing in tasks and risks for sheets and calendar when it's Ongoing.
  app/javascript/components/dashboard/risks/calendar/risk_calendar.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/tasks/task_calendar.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
Labels: security findings

#3089 Hotfix for last update time displaying as current time.
  app/javascript/components/dashboard/issues/issue_index.vue
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/issues/issue_sheets_index.vue
  app/javascript/components/dashboard/risks/risk_index.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_index.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
Labels: HOTFIX

#3100 Backend solution for Last Update order bug
  app/javascript/components/dashboard/issues/issue_index.vue
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/issues/issue_sheets_index.vue
  app/javascript/components/dashboard/risks/risk_index.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets_index.vue
  app/javascript/components/dashboard/tasks/task_index.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
  app/models/issue.rb
  app/models/lesson.rb
  app/models/risk.rb
  app/models/task.rb
Labels: security findings

#3097 Reverted status enumeration implementation
  app/models/issue.rb
  app/models/risk.rb
  app/models/task.rb
  db/migrate/20210715172225_remove_status_field_in_tables.rb
Labels: security findings

#3088 Adding pagination in portfolio service
  app/controllers/api/v1/portfolio_controller.rb
  app/controllers/projects_controller.rb
  app/models/lesson.rb
  config/routes.rb
Labels: security findings

#3093 Readded the edit and delete actions for notes on sheet tab.
  app/javascript/components/dashboard/members_view.vue
  app/javascript/components/dashboard/notes/notes_sheets.vue
  app/javascript/components/dashboard/tasks/task_form.vue
Labels: security findings

#3095 Setting log configuration to rotate log
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: security findings

#3108 Fix routing issue and add authorization check
  app/controllers/dashboard_controller.rb
  app/controllers/projects_controller.rb
  app/javascript/components/users/profile.vue
  app/models/user.rb
  app/views/layouts/_landing.html.slim
Labels: security findings

#3103 Fix: Admin lesson file download link page crash
  app/admin/issues.rb
  app/admin/lessons.rb
  app/admin/risks.rb
  app/admin/tasks.rb
  app/models/concerns/admin_utility.rb
Labels: security findings

#3109 Remove privileges of user is removed from project
  app/admin/projects.rb
  app/models/privilege.rb
  app/models/project_privilege.rb
  app/models/user.rb
  app/views/admin/facility_privileges/facility_privileges_partial.html.slim
Labels: security findings

#3112 Multiple changes to data outputs on Portfolio View
  app/javascript/components/dashboard/issues/issue_sheets.vue
  app/javascript/components/dashboard/risks/sheets/risk_sheets.vue
  app/javascript/components/dashboard/tasks/task_sheets.vue
  app/javascript/components/views/portfolio/PortfolioView.vue
Labels: security findings

#3123 2518 - Progress bar not display Adv Filters
  app/javascript/components/shared/filter_sidebar.vue
Labels: security findings

#3122 Fix the issue with admin panel
  app/admin/issues.rb
  app/admin/lessons.rb
  app/admin/risks.rb
  app/admin/tasks.rb
Labels: security findings

#3124 Added Issue Severity and Risk Approach and Priority Level tables.
  app/javascript/components/views/portfolio/PortfolioView.vue
Labels: security findings

#3126 WIP: JWT Authentication
  Gemfile
  Gemfile.lock
  app/controllers/api/application_controller.rb
  app/controllers/api/authentication_controller.rb
  app/controllers/api/statuses_controller.rb
  app/controllers/api/v1/issues_controller.rb
  app/controllers/api/v1/lessons_controller.rb
  app/controllers/api/v1/notes_controller.rb
  app/controllers/api/v1/portfolio_controller.rb
  app/controllers/api/v1/profiles_controller.rb
  app/controllers/api/v1/projects_controller.rb
  app/controllers/api/v1/risks_controller.rb
  app/controllers/api/v1/tasks_controller.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/initializers/jwt.rb
  config/routes.rb
  lib/json_web_token.rb
Labels: security findings

#3129 Changed images for completed and ongoing on the table to be the same from the filter.
  app/javascript/components/views/portfolio/PortfolioView.vue
Labels: security findings

#3125 Updates and SFBPs will not save if they do not meet the requirements.
  app/javascript/components/dashboard/lessons/LessonForm.vue
Labels: security findings

#3133 Fix portoflio view
  app/controllers/api/v1/portfolio_controller.rb
  app/controllers/application_controller.rb
  app/controllers/lessons_controller.rb
  app/models/facility_project.rb
  app/models/project.rb
  config/routes.rb
Labels: security findings

#3135 Remove write and delete if read privilege is removed
  app/models/facility_privilege.rb
  app/models/privilege.rb
  app/models/project_privilege.rb
Labels: security findings

#3151 Fix error on admin panel
  app/models/facility_privilege.rb
  app/models/privilege.rb
  app/models/project_privilege.rb
Labels: security findings

#3160 Fix routing issue
  app/javascript/components/users/profile.vue
  app/models/user.rb
Labels: security findings

#3144 Fix file links in lesson, task, risk and issues
  app/admin/issues.rb
  app/admin/lessons.rb
  app/admin/risks.rb
  app/admin/tasks.rb
  app/models/concerns/admin_utility.rb
  app/models/issue.rb
  app/models/lesson.rb
  app/models/risk.rb
  app/models/task.rb
  vendor/assets/javascripts/active_admin.js
Labels: security findings

#3167 Portfolio 23 jul
  app/controllers/api/v1/portfolio_controller.rb
  app/javascript/components/dashboard/tasks/task_sheets_index.vue
  app/javascript/components/shared/ProjectRollup.vue
  app/javascript/components/views/map/MapLessons.vue
  app/javascript/components/views/portfolio/PortfolioView.vue
  app/javascript/components/views/sheet/SheetLessons.vue
  app/models/facility.rb
  app/models/issue.rb
  app/models/lesson.rb
  app/models/note.rb
  app/models/project.rb
  app/models/risk.rb
  app/models/task.rb
  app/models/user.rb
Labels: security findings

#3146 Rake task to print list of task, issue and risk and their statuses
  lib/tasks/print_statuses.rake
Labels: security findings
